#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_6
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_7
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_11


#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_10
//#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_3
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_18
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_2

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif


#define BOOT_BUTTON_GPIO        GPIO_NUM_9
#define ASR_BUTTON_GPIO GPIO_NUM_19


#define I2C_SDA_PIN  GPIO_NUM_4
#define I2C_SCL_PIN  GPIO_NUM_5

#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64


#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#endif // _BOARD_CONFIG_H_